linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - unused
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goerr113
    - gofmt
    - goimports
    - revive
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - rowserrcheck
    - exportloopref
    - staticcheck
    - stylecheck
    - testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  # come back to this.  might be useful later.
  # - prealloc
  # - wsl
  #
  # probably not worrying about this.
  # - godox
